Django/network/network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from network import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('social/', include('social.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/network/user/urls.py
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    path('create/', views.render_register_user_form, name='create'),
    path('register/', views.process_register_user_form, name='register'),
    path('login/', views.render_login_user_form, name='login'),
    path('authorize/', views.process_login_user_form, name='authorize'),
]

Django/network/user/models.py
from django.db import models


class User(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    date_of_birth = models.DateField()
    phone_number = models.IntegerField(unique=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=30)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

Django/network/user/views.py
from django.shortcuts import render, reverse, HttpResponse, HttpResponseRedirect
from user.models import User


def render_register_user_form(request):
    template = 'user/register_user_form.html'
    return render(request, template)


def process_register_user_form(request):
    if request.method == 'POST':
        new_user = User(
            first_name=request.POST['first_name'],
            last_name=request.POST['last_name'],
            date_of_birth=request.POST['date_of_birth'],
            phone_number=request.POST['phone_number'],
            gender=request.POST['gender'],
            email=request.POST['email'],
            password=request.POST['password']
        )
        new_user.save()

        return HttpResponseRedirect(reverse('user:login'))
    return HttpResponse('Error: method not allowed.')


def render_login_user_form(request):
    template = 'user/login_user_form.html'
    return render(request, template)


def process_login_user_form(request):
    if request.method == 'POST':
        try:
            user = User.objects.get(email=request.POST['email'], password=request.POST['password'])
        except User.DoesNotExist:
            return HttpResponse('User does not exist.')

        return HttpResponseRedirect(reverse('social:index', kwargs={'user_id': user.pk}))
    return HttpResponse('Error:method not allowed.')

Django/network/user/templates/user/login_user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form action="{% url 'user:authorize' %}" method="post">{% csrf_token %}
        <p><label>Email: </label><input type="text" name="email"></p>
        <p><label>Password: </label><input type="password" name="password"></p>
        <p><input type="submit" value="Login"></p>
    </form>
</body>
</html>

Django/network/user/templates/user/register_user_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
</head>
<body>
    <h1>Register</h1>
    <form action="{% url 'user:register' %}" method="post">{% csrf_token %}
        <p><label>First Name: </label><input type="text" name="first_name"></p>
        <p><label>Last Name: </label><input type="text" name="last_name"></p>
        <p><label>Date of Birth: </label><input type="date" name="date_of_birth"></p>
        <p><label>Phone Number: </label><input type="text" name="phone_number"></p>
        <p><label>Gender: </label><label>Male</label><input type="radio" name="gender" value="male"><label>Female</label><input type="radio" name="gender" value="female"></p>
        <p><label>Email: </label><input type="text" name="email"></p>
        <p><label>Password: </label><input type="password" name="password"></p>
        <p><input type="submit" value="Register"></p>
    </form>
</body>
</html>