Django/network/network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from network import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('social/', include('social.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/network/social/urls.py
from django.urls import path
from social import views


app_name = 'social'
urlpatterns = [
    path('index/<int:user_id>', views.render_index, name='index'),
    path('activity/<int:user_id>', views.render_activity_form, name='activity'),
    path('add/', views.process_activity_form, name='add'),
    path('edit/<int:activity_id>', views.render_edit_activity_form, name='edit'),
    path('save_edit/<int:activity_id>', views.process_edit_activity_form, name='save_edit'),
    path('delete/<int:activity_id>', views.delete_activity, name='delete'),
    path('group/', views.render_group_form, name='group'),
    path('make/', views.process_group_form, name='make'),
    path('group_list/', views.GroupView.as_view(), name='group_list'),
    path('join_group/', views.GroupView.as_view(), name='join_group'),
    path('event/', views.render_event_form, name='event'),
    path('new_event/', views.process_event_form, name='new_event'),
    path('event_list/', views.EventView.as_view(), name='event_list'),
    path('assist_event/', views.EventView.as_view(), name='assist_event'),
]

Django/network/user/urls.py
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    path('create/', views.render_register_user_form, name='create'),
    path('register/', views.process_register_user_form, name='register'),
    path('login/', views.render_login_user_form, name='login'),
    path('authorize/', views.process_login_user_form, name='authorize'),
]

Django/network/social/models.py
from django.db import models
from user.models import User


class Activity(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner')
    picture = models.ImageField(upload_to='images')
    text = models.TextField(blank=True)


class Group(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name


class GroupUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)


class Event(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return self.name


class EventUser(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

Django/network/social/forms.py
from django import forms
from .models import *


class ActivityForm(forms.ModelForm):

    class Meta:
        model = Activity
        fields = ['text', 'picture']

Django/network/social/views.py
from django.shortcuts import render, reverse, HttpResponse, HttpResponseRedirect, redirect
from social.models import Activity, Group, Event, EventUser, GroupUser
from user.models import User
from django.views.generic import ListView


def render_index(request, user_id):
    template = 'social/index.html'
    context = {
        'index': Activity.objects.all,
        'user': user_id
    }
    return render(request, template, context)


def render_activity_form(request, user_id):
    template = 'social/activity_form.html'
    context = {
        'user': user_id
    }
    return render(request, template, context)


def process_activity_form(request):
    if request.method == 'POST':
        owner = User.objects.get(pk=request.POST['owner_id'])
        new_activity = Activity(
            picture=request.FILES['picture'],
            text=request.POST['text'],
            owner=owner,
        )
        new_activity.save()

        return HttpResponseRedirect(reverse('social:index', kwargs={'user_id': new_activity.owner.id}))
    return HttpResponse('Error: method not allowed.')


def render_edit_activity_form(request, activity_id):
    template = 'social/edit_activity_form.html'
    context = {
        'activity': Activity.objects.get(id=activity_id)
    }
    return render(request, template, context)


def process_edit_activity_form(request, activity_id):
    if request.method == 'POST':
        updated_activity = Activity.objects.get(id=activity_id)
        updated_activity.picture = request.FILES['picture']
        updated_activity.text = request.POST['text']
        updated_activity.save()

        return HttpResponseRedirect(reverse('social:index', kwargs={'user_id': updated_activity.user.id}))
    return HttpResponse('Error: method not allowed.')


def delete_activity(request, activity_id):
    deleted_activity = Activity.objects.get(id=activity_id)
    deleted_activity.delete()

    return HttpResponseRedirect(reverse('social:index', kwargs={'user_id': deleted_activity.owner.id}))


def render_group_form(request):
    template = 'social/group_form.html'
    return render(request, template)


def process_group_form(request):
    if request.method == 'POST':
        new_group = Group(
            name=request.POST['name'],
            description=request.POST['description'],
        )
        new_group.save()

        return HttpResponseRedirect(reverse('social:index', kwargs={'group_id': new_group.id}))
    return HttpResponse('Error: method not allowed.')


class GroupView(ListView):
    model = Group
    fields = '__all__'
    context_object_name = 'group_list'


def join_group(request, group_id, user_id):
    joined_group = Group.objects.get(id=group_id)
    user_joined = User.objects.get(id=user_id)
    GroupUser.add(joined_group, user_joined)

    return HttpResponseRedirect(reverse('social:group_list'))


def render_event_form(request):
    template = 'social/event_form.html'
    return render(request, template)


def process_event_form(request, user_id):
    if request.method == 'POST':
        user = EventUser.request.POST(id=user_id)
        new_event = Event(
            name=request.POST['name'],
            description=request.POST['description'],
            date=request.POST['date'],
            start_time=request.POST['start_time'],
            end_time=request.POST['end_time'],
            user=request.POST['user'],
        )
        new_event.save()
        return HttpResponseRedirect(reverse('social:index', kwargs={'user_id': new_event.user.id}))
    return HttpResponse('Error: method not allowed.')


class EventView(ListView):
    model = Event
    fields = '__all__'
    context_object_name = 'event_list'


def assist_event(request, user_id, event_id):
    chosen_event = Event.objects.get(id=event_id)
    user = User.objects.get(id=user_id)
    EventUser.add(chosen_event, user)

Django/network/social/templates/social/activity_form.html
{% extends 'social/base.html' %}

{% block content %}
    <h1>Add a picture</h1>
        <form action="{% url 'social:add' %}" method="post" enctype='multipart/form-data'>{% csrf_token %}
            <p class="form-group"><label class="mr-sm-2">Add a Picture: </label><input type="file" name="picture"></p>
            <p class="form-group"><label class="mr-sm-2">Add a Text: </label><input type="text" name="text"></p>
            <p><input type="hidden" name="owner_id" value="{{user}}"></p>
            <input type="submit" class="btn btn-light btn-outline-secondary" value="Add" />
        </form>
{% endblock %}

Django/network/social/templates/social/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
        {% load static %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'social/style.css' %}">
</head>
<body>
 {% block content %}{% endblock %}
</body>
</html>

Django/network/social/templates/social/edit_activity_form.html
{% extends 'social/base.html' %}

{% block content %}
    <h1>Edit picture</h1>
        <form action="{% url 'social:save_edit' activity.id %}" method="post" enctype='multipart/form-data'>{% csrf_token %}
            <p class="form-group"><label class="mr-sm-2">Add a Picture: </label><input type="file" name="picture"></p>
            <p class="form-group"><label class="mr-sm-2">Add a Text: </label><input type="text" name="text"></p>
            <p><input type="hidden" name="owner_id" value="{{user}}"></p>
            <input type="submit" class="btn btn-light btn-outline-secondary" value="Add" />
        </form>
{% endblock %}

Django/network/social/templates/social/event_form.html
{% extends 'social/base.html' %}

{% block content %}
    <h1>New Event</h1>
    <form action="{% url 'social:new_event' %}" method="post" class="form-inline">{% csrf_token %}
        <p class="form-group m"><label class="mr-sm-2">Name: </label><input type="text" name="name" class="mr-sm-4"></p>
        <p class="form-group m"><label class="mr-sm-2">Description: </label><input type="text" name="description" class="mr-sm-4"></p>
        <p class="form-group m"><label class="mr-sm-2">Date: </label><input type="date" name="date" class="mr-sm-4"></p>
        <p class="form-group m"><label class="mr-sm-2">Start Time: </label><input type="time" name="start_time" class="mr-sm-4"></p>
        <p class="form-group m"><label class="mr-sm-2">End Time: </label><input type="time" name="end_time" class="mr-sm-4"></p>
        <input type="submit" class="btn btn-light btn-outline-secondary" value="Add event" />
    </form>
{% endblock %}

Django/network/social/templates/social/event_list.html
{% extends 'social/base.html' %}

{% block content %}
<h1>Your events</h1>

<ul>
    {% for event in event_list %}
    <li><h4>{{ event.name }}</h4></li>
    <li>{{ event.description }} </li>
    <li>{{ event.date }} -- {{ event.start_time }} -- {{ event.end_time }}</li><br>
    <li><button><a href="{% url 'social:assist_event' %}">Assist</a></button></li>

    <button><a href="{% url 'social:index' user %}">Go back to index</a></button>
    {% empty %}
    <li>Empty</li>
    {% endfor %}
</ul>
{% endblock %}

Django/network/social/templates/social/group_form.html
{% extends 'social/base.html' %}

{% block content %}
    <h1>Create Group</h1>
        <form action="{% url 'social:make' %}" method="post">{% csrf_token %}
            <p class="form-group"><label class="mr-sm-2">Name: </label><input type="text" name="name"></p>
            <p class="form-group"><label class="mr-sm-2">Description: </label><input type="text" name="description"></p>
            <input type="submit" class="btn btn-light btn-outline-secondary" value="Create Group" />
        </form>
{% endblock %}

Django/network/social/templates/social/group_list.html
{% extends 'social/base.html' %}

{% block content %}
<h1>Your groups</h1>

<ul>
    {% for group in group_list %}
    <li><h4>{{ group.name }}</h4></li>
    <li>{{ group.description }} </li><br>
    <li><button><a href="{% url 'social:join_group' %}">Join Group</a></button></li>

    <h4><button><a href="{% url 'social:index' user %}">Go back to index</a></button></h4>
    {% empty %}
    <li>Empty</li>
    {% endfor %}
</ul>
{% endblock %}

Django/network/social/templates/social/index.html
{% extends 'social/base.html' %}

{% block content %}
    <button class="btn btn-light btn-outline-secondary"><a href="{% url 'social:activity' user %}">Add a picture</a></button>
    <button class="btn btn-light btn-outline-secondary"><a href="{% url 'social:event' user %}">Add an event</a></button>
    <button class="btn btn-light btn-outline-secondary"><a href="{% url 'social:event_list' %}">Show events</a></button>
    <button class="btn btn-light btn-outline-secondary"><a href="{% url 'social:group' %}">Create a group</a></button>
    <button class="btn btn-light btn-outline-secondary"><a href="{% url 'social:group_list' %}">Show groups</a></button>

    <h1>Thread</h1>
    {% if index %}
        {% for info in index %}
        <p><img src="{{ info.picture.url }}" class="rounded"></p>
        <p>{{ info.text }} (<a href="{% url 'social:edit' info.id %}">edit</a>) (<a href="{% url 'social:delete' info.id %}">delete</a>)</p>
        {% endfor %}
    {% else %}
        <p>Nothing to show.</p>
    {% endif %}
{% endblock %}